databases:
  - name: university-scheduler-db
    databaseName: scheduler_db
    user: scheduler_user
    plan: free

services:
  - type: web
    name: university-scheduler
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn scheduler_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "university-scheduler.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: university-scheduler-db
          property: connectionString
