# Generated by Django 4.2.7 on 2026-03-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batchsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubjectCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_capabilities', to='core.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capable_faculty', to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Faculty Subject Capabilities',
                'unique_together': {('faculty', 'subject')},
            },
        ),
    ]
