# Generated by Django 4.2.7 on 2026-05-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_combined_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='combined_class',
            field=models.ForeignKey(blank=True, help_text='Set if this entry was created from a combined class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='core.combinedclass'),
        ),
    ]
