# Generated by Django 4.2.7 on 2026-05-02 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timetableentry_combined_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Auto-generated label', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_timetables', to='core.batch')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_combined', models.BooleanField(default=False)),
                ('combined_batch_sections', models.CharField(blank=True, max_length=500)),
                ('saved_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.savedtimetable')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
