# Generated by Django 4.2.7 on 2026-05-02 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saved_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Department Coordinator'), ('reviewer', 'Reviewer'), ('class_advisor', 'Class Advisor')], default='coordinator', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_advisor', to='core.batch')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_advisor_profile', to='core.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_advisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch'],
            },
        ),
    ]
