# Generated by Django 6.0.4 on 2026-05-06 01:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning Shift, Afternoon Shift', max_length=100)),
                ('start_time', models.IntegerField(help_text='Shift start hour (6-14), e.g. 8 for 8:00 AM', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(14)])),
                ('end_time', models.IntegerField(help_text='Shift end hour (12-22), e.g. 17 for 5:00 PM', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(22)])),
                ('lunch_start', models.IntegerField(help_text='Lunch break start hour, e.g. 13 for 1:00 PM', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(16)])),
                ('lunch_duration', models.IntegerField(default=1, help_text='Lunch break duration in hours (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Working hours shift for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.shift'),
        ),
    ]
