# Generated by Django 6.0.4 on 2026-05-06 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shift_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedclass',
            name='end_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AlterField(
            model_name='combinedclass',
            name='start_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
